name: DriverService CI

on:
  push:
    paths: ['DriverService/**']

jobs:
  linting:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      working_dir: './DriverService'

  test-and-build:
    needs: linting 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
